### ISSUE TITLE
建议: 多平台自动适配

### ISSUE THREAD

**Issue by phlinhng** [DongfeiSay/trojan-go-quickstart#1]
trojan-go 有多平台版本，可以参考 v2ray 的脚本做自动适配，脚本会更通用。https://github.com/v2fly/fhs-install-v2ray/blob/master/install-release.sh

**Comment by DongfeiSay** [comment]
暂时先不考虑，虽然 trojan-go 有多平台版本，但是估计有9成都是在amd64上部署的，并且路径和命令在其他平台上未必通用，也会使得之后的维护更加困难，因此开始的选择是和 trojan-quickstart 一样只支持linux-amd64。
